version: '3.8'

networks:
  app-tier:
    driver: bridge

volumes:
  opensearch_data:
    driver: local
    driver_opts:
      type: none
      device: data/opensearch/
      o: bind

services:
  postgres:
    image: postgres:17.0-alpine
    restart: always
    ports:
      - 15432:5432
    networks:
      - app-tier
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES__USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DB}
    volumes:
      - ./data/pg_history:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USERNAME} -d ${POSTGRES__DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - logger.level=ERROR
      - rootLogger.level=ERROR
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 19200:9200
      - 19600:9600
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 3G
    restart: always
    networks:
      - app-tier

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    restart: always
    networks:
      - app-tier

  litellm_service:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "9510:4000"
    networks:
      - app-tier
    volumes:
      - ./config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    environment:
      - GEMINI_API_KEY1=${GEMINI_API_KEY1}


