"""add_type_recommend_to_recommend_items

Revision ID: 883d0a661ca4
Revises: 6402eec131e8
Create Date: 2026-01-22 12:51:27.244346

"""
from __future__ import annotations

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '883d0a661ca4'
down_revision: Union[str, None] = '6402eec131e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('recommend_items', sa.Column('type_recommend', sa.String(), nullable=True))
    # Set a default value for existing rows (change 'unknown' to your preferred default)
    op.execute("UPDATE recommend_items SET type_recommend = 'content' WHERE type_recommend IS NULL")
    # Make the column non-nullable
    op.alter_column('recommend_items', 'type_recommend', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommend_items', 'type_recommend')
    # ### end Alembic commands ###
