"""add is_confirm in conversation table

Revision ID: cd17e5bf74a3
Revises: cfbdfc083d01
Create Date: 2026-02-25 01:19:14.534452

"""
from __future__ import annotations

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cd17e5bf74a3'
down_revision: Union[str, None] = 'cfbdfc083d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('is_confirming', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'is_confirming')
    # ### end Alembic commands ###
