"""add text2sql tables

Revision ID: cfbdfc083d01
Revises: 804d62a26efd
Create Date: 2026-02-04 14:53:18.608864

"""
from __future__ import annotations

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfbdfc083d01'
down_revision: Union[str, None] = '804d62a26efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'policy_rule',
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_policy_rule_id'), 'policy_rule', ['id'], unique=False)
    op.create_table(
        'addresses',
        sa.Column('city_id', sa.String(), nullable=True),
        sa.Column('region', sa.String(), nullable=True),
        sa.Column('country_code', sa.String(), nullable=True),
        sa.Column('ward', sa.String(), nullable=True),
        sa.Column('detail', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table(
        'brands',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.Column('contact_name', sa.String(), nullable=True),
        sa.Column('contact_phone', sa.String(), nullable=True),
        sa.Column('address_id', sa.String(), nullable=True),
        sa.Column('join_date', sa.DateTime(), nullable=True),
        sa.Column('last_active', sa.DateTime(), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('meta_title', sa.String(), nullable=True),
        sa.Column('meta_description', sa.String(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table(
        'inventories',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('address_id', sa.String(), nullable=True),
        sa.Column('contact_name', sa.String(), nullable=True),
        sa.Column('contact_phone', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
    )
    op.create_index(op.f('ix_inventories_id'), 'inventories', ['id'], unique=False)
    op.create_table(
        'carts',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('total_price', sa.Float(), nullable=False),
        sa.Column('total_quantity', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table(
        'orders',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('address_id', sa.String(), nullable=True),
        sa.Column('total_price', sa.Float(), nullable=False),
        sa.Column('order_status', sa.String(), nullable=False),
        sa.Column('shipping_fee', sa.Float(), nullable=False),
        sa.Column('subtotal_price', sa.Float(), nullable=False),
        sa.Column('discount_total', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('payment_status', sa.String(), nullable=False),
        sa.Column('cancel_reason', sa.String(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table(
        'user_attributes',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('summarize_attribute', sa.String(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_attributes_id'), 'user_attributes', ['id'], unique=False)
    op.create_table(
        'user_authentications',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('social_id', sa.String(), nullable=True),
        sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.create_index(op.f('ix_user_authentications_id'), 'user_authentications', ['id'], unique=False)
    op.create_table(
        'payments',
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('payment_method', sa.String(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('transaction_code', sa.String(), nullable=False),
        sa.Column('payment_provider', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table(
        'product_categories',
        sa.Column('product_id', sa.String(), nullable=False),
        sa.Column('category_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_table(
        'product_variants',
        sa.Column('product_id', sa.String(), nullable=False),
        sa.Column('sku', sa.String(), nullable=False),
        sa.Column('barcode', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('weight_g', sa.Float(), nullable=True),
        sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sku'),
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_table(
        'cart_items',
        sa.Column('cart_id', sa.String(), nullable=False),
        sa.Column('product_variant_id', sa.String(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('is_selected', sa.Boolean(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_table(
        'human_activities',
        sa.Column('message_id', sa.String(), nullable=True),
        sa.Column('product_variant_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('action_type', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('search_keyword', sa.String(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_human_activities_id'), 'human_activities', ['id'], unique=False)
    op.create_table(
        'order_items',
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('product_variant_id', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table(
        'reviews',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('product_variant_id', sa.String(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.String(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table(
        'variant_inventories',
        sa.Column('inventory_id', sa.String(), nullable=False),
        sa.Column('product_variant_id', sa.String(), nullable=False),
        sa.Column('stock_on_hand', sa.Integer(), nullable=False),
        sa.Column('stock_reserved', sa.Integer(), nullable=False),
        sa.Column('reorder_point', sa.Integer(), nullable=False),
        sa.Column('last_stocktake_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_variant_inventories_id'), 'variant_inventories', ['id'], unique=False)
    op.drop_index('ix_product_category_id', table_name='product_category')
    op.drop_table('product_category')
    op.drop_index('ix_human_activity_log_id', table_name='human_activity_log')
    op.drop_table('human_activity_log')
    op.drop_index('ix_user_attribute_id', table_name='user_attribute')
    op.drop_table('user_attribute')
    op.drop_index('ix_user_authentication_id', table_name='user_authentication')
    op.drop_table('user_authentication')
    op.add_column('city', sa.Column('code', sa.String(), nullable=True))
    op.add_column('city', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('group', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('group', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('group', sa.Column('meta_title', sa.String(), nullable=True))
    op.add_column('group', sa.Column('meta_description', sa.String(), nullable=True))
    op.add_column('product', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('product', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('product', sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('status', sa.String(), nullable=True))
    op.add_column('product', sa.Column('brand_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'product', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    op.drop_column('product', 'price')
    op.drop_column('product', 'brand')
    op.drop_column('product', 'size')
    op.drop_column('product', 'weight')
    op.drop_column('product', 'stock')
    op.drop_column('product', 'material')
    op.drop_column('product', 'image_url')
    op.add_column('user', sa.Column('address_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avt_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(), nullable=True))
    op.alter_column(
        'user', 'dob',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        'user', 'phone',
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        'user', 'gender',
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        'user', 'last_active',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_constraint('user_city_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user', 'name')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'ward')
    op.drop_column('user', 'address')
    op.drop_column('user', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('ward', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_city_id_fkey', 'user', 'city', ['city_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column(
        'user', 'last_active',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        'user', 'gender',
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        'user', 'phone',
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        'user', 'dob',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column('user', 'status')
    op.drop_column('user', 'avt_url')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'address_id')
    op.add_column('product', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('weight', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('size', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'brand_id')
    op.drop_column('product', 'status')
    op.drop_column('product', 'image_urls')
    op.drop_column('product', 'thumbnail_url')
    op.drop_column('product', 'origin')
    op.drop_column('group', 'meta_description')
    op.drop_column('group', 'meta_title')
    op.drop_column('group', 'icon_url')
    op.drop_column('group', 'slug')
    op.drop_column('city', 'is_active')
    op.drop_column('city', 'code')
    op.create_table(
        'user_authentication',
        sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('deletedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='user_authentication_pkey'),
        sa.UniqueConstraint('username', name='user_authentication_username_key'),
    )
    op.create_index('ix_user_authentication_id', 'user_authentication', ['id'], unique=False)
    op.create_table(
        'user_attribute',
        sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('summarize_attribute', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('deletedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_attribute_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='user_attribute_pkey'),
    )
    op.create_index('ix_user_attribute_id', 'user_attribute', ['id'], unique=False)
    op.create_table(
        'human_activity_log',
        sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('deletedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='human_activity_log_message_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='human_activity_log_product_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='human_activity_log_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='human_activity_log_pkey'),
    )
    op.create_index('ix_human_activity_log_id', 'human_activity_log', ['id'], unique=False)
    op.create_table(
        'product_category',
        sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('deletedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='product_category_category_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_category_product_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='product_category_pkey'),
    )
    op.create_index('ix_product_category_id', 'product_category', ['id'], unique=False)
    op.drop_index(op.f('ix_variant_inventories_id'), table_name='variant_inventories')
    op.drop_table('variant_inventories')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_human_activities_id'), table_name='human_activities')
    op.drop_table('human_activities')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_user_authentications_id'), table_name='user_authentications')
    op.drop_table('user_authentications')
    op.drop_index(op.f('ix_user_attributes_id'), table_name='user_attributes')
    op.drop_table('user_attributes')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_inventories_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_policy_rule_id'), table_name='policy_rule')
    op.drop_table('policy_rule')
    # ### end Alembic commands ###
