"""add summarize for conversation table

Revision ID: de6fc8efca25
Revises: 636cde55537b
Create Date: 2025-12-19 13:12:58.045704

"""
from __future__ import annotations

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'de6fc8efca25'
down_revision: Union[str, None] = '636cde55537b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('summary', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'summary')
    # ### end Alembic commands ###
