"""Initial migration

Revision ID: a0cff2a8a45b
Revises: 
Create Date: 2026-01-14 00:46:43.690046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0cff2a8a45b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_component',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provinces_id'), 'provinces', ['id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('province_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=True),
    sa.Column('administrative_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_districts_admin_id', 'districts', ['administrative_id'], unique=False)
    op.create_index('idx_districts_name', 'districts', ['name'], unique=False)
    op.create_index('idx_districts_province', 'districts', ['province_id'], unique=False)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_table('distric_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Text(), nullable=False),
    sa.Column('aqi_value', sa.Integer(), nullable=True),
    sa.Column('pm25_value', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stats_component', 'distric_stats', ['component_id'], unique=False)
    op.create_index('idx_stats_date', 'distric_stats', ['date'], unique=False)
    op.create_index('idx_stats_date_district', 'distric_stats', ['date', 'district_id'], unique=False)
    op.create_index('idx_stats_district', 'distric_stats', ['district_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stats_district', table_name='distric_stats')
    op.drop_index('idx_stats_date_district', table_name='distric_stats')
    op.drop_index('idx_stats_date', table_name='distric_stats')
    op.drop_index('idx_stats_component', table_name='distric_stats')
    op.drop_table('distric_stats')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index('idx_districts_province', table_name='districts')
    op.drop_index('idx_districts_name', table_name='districts')
    op.drop_index('idx_districts_admin_id', table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_provinces_id'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_table('air_component')
    # ### end Alembic commands ###
